baseurl: /portfolio
exclude: [README.md]
exclude: [assets/css/somuchstyle.css]

collections:
    projetos:
        output: true
        permalink: /projetos/:categories/:path/
        sort_by: category